language: node_js
node_js:
  - lts/*
script:
  - yarn install
  - yarn test
  - yarn lint
  - yarn docs:build
  - yarn test:e2e:ci
deploy:
  local_dir: docs/dist
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
